format = """
[╭─](dimmed) $directory$git_branch$git_status$cmd_duration
[╰─](dimmed) $character"""

add_newline = false

[directory]
style = "bold cyan"
format = "[$path]($style) "
truncation_length = 3
truncate_to_repo = false

[git_branch]
symbol = " "
style = "green"
format = "[$symbol$branch]($style) "

[git_status]
style = "yellow"
format = "([$all_status$ahead_behind]($style) )"

[cmd_duration]
min_time = 5000
style = "dimmed"
format = "took [$duration]($style) "

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
