# Pukka-KDE Zsh configuration

HISTFILE=~/.histfile
HISTSIZE=5000
SAVEHIST=5000

setopt autocd beep extendedglob nomatch notify

bindkey -e
bindkey '^[[H' beginning-of-line
bindkey '^[[F' end-of-line
bindkey '^[[3~' delete-char

autoload -Uz compinit
compinit

eval "$(starship init zsh)"

if [[ -r /usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh ]]; then
    source /usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh
fi

if [[ -r /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ]]; then
    source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
fi

# Pukka-KDE: Startup animation
if [[ $- == *i* ]]; then
    zsh "${XDG_CONFIG_HOME:-$HOME/.config}/pukka-kde/animation.zsh"
fi
